
CREATE TABLE usuarios
(
	ID_USUARIO INT(15) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOMBRE VARCHAR(60) NOT NULL,
	APELLIDO VARCHAR(60) NOT NULL,
	USUARIO VARCHAR(40) NOT NULL,
	PASSWORD VARCHAR(80) NOT NULL,
	PERFIL VARCHAR(30) NOT NULL,
	ESTADO VARCHAR(20) NOT NULL
);

CREATE TABLE materia
(
	ID_MATERIA INT(15) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	MATERIA VARCHAR(30) NOT NULL
);

CREATE TABLE estudiantes
(
	ID_ESTUDIANTES INT(15) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOMBRE VARCHAR(60) NOT NULL,
	APELLIDO VARCHAR(60) NOT NULL,
	DOCUMENTO VARCHAR(12) NOT NULL,
	CORREO VARCHAR(60) NOT NULL,
	MATERIA VARCHAR(30) NOT NULL,
	DOCENTE VARCHAR(60) NOT NULL,
	PROMEDIO INT(3) NOT NULL,
	FECHA_REGISTRO DATE NOT NULL
);